In [1]:
import numpy as np
import pandas as pd

In [2]:
d1=pd.read_csv('New_Car_Automobile.csv')

In [3]:
d1

car-name fuel-type aspiration num-of-doors   body-style drive-wheels  \
0     alfa-romero       gas        std          two  convertible          rwd   
1     alfa-romero       gas        std          two  convertible          rwd   
2     alfa-romero       gas        std          two    hatchback          rwd   
3            audi       gas        std         four        sedan          fwd   
4            audi       gas        std         four        sedan          4wd   
...           ...       ...        ...          ...          ...          ...   
2045        volvo       gas        std         four        sedan          rwd   
2046        volvo       gas      turbo         four        sedan          rwd   
2047        volvo       gas        std         four        sedan          rwd   
2048        volvo    diesel      turbo         four        sedan          rwd   
2049        volvo       gas      turbo         four        sedan          rwd   

     engine-location  wheel-base  length  width  ...  engine-size  \
0              front        88.6   168.8   64.1  ...          130   
1              front        88.6   168.8   64.1  ...          130   
2              front        94.5   171.2   65.5  ...          152   
3              front        99.8   176.6   66.2  ...          109   
4              front        99.4   176.6   66.4  ...          136   
...              ...         ...     ...    ...  ...          ...   
2045           front       109.1   188.8   68.9  ...          141   
2046           front       109.1   188.8   68.8  ...          141   
2047           front       109.1   188.8   68.9  ...          173   
2048           front       109.1   188.8   68.9  ...          145   
2049           front       109.1   188.8   68.9  ...          141   

      fuel-system  bore stroke  compression-ratio horsepower  peak-rpm  \
0            mpfi  3.47   2.68          10.779306      111.0    5000.0   
1            mpfi  3.47   2.68          10.779306      111.0    5000.0   
2            mpfi  2.68   3.47          10.779306      154.0    5000.0   
3            mpfi  3.19   3.40          10.000000      102.0    5500.0   
4            mpfi  3.19   3.40          10.779306      115.0    5500.0   
...           ...   ...    ...                ...        ...       ...   
2045         mpfi  3.78   3.15           9.500000      114.0    5400.0   
2046         mpfi  3.78   3.15           8.700000      160.0    5300.0   
2047         mpfi  3.58   2.87           8.800000      134.0    5500.0   
2048          idi  3.01   3.40          23.000000      106.0    4800.0   
2049         mpfi  3.78   3.15           9.500000      114.0    5400.0   

      city-mpg  highway-mpg    price  
0           21           27  13495.0  
1           21           27  16500.0  
2           19           26  16500.0  
3           24           30  13950.0  
4           18           22  17450.0  
...        ...          ...      ...  
2045        23           28  16845.0  
2046        19           25  19045.0  
2047        18           23  21485.0  
2048        26           27  22470.0  
2049        19           25  22625.0  

[2050 rows x 24 columns]

In [4]:
x=d1.drop('price',axis=1)

In [5]:
x

car-name fuel-type aspiration num-of-doors   body-style drive-wheels  \
0     alfa-romero       gas        std          two  convertible          rwd   
1     alfa-romero       gas        std          two  convertible          rwd   
2     alfa-romero       gas        std          two    hatchback          rwd   
3            audi       gas        std         four        sedan          fwd   
4            audi       gas        std         four        sedan          4wd   
...           ...       ...        ...          ...          ...          ...   
2045        volvo       gas        std         four        sedan          rwd   
2046        volvo       gas      turbo         four        sedan          rwd   
2047        volvo       gas        std         four        sedan          rwd   
2048        volvo    diesel      turbo         four        sedan          rwd   
2049        volvo       gas      turbo         four        sedan          rwd   

     engine-location  wheel-base  length  width  ...  num-of-cylinders  \
0              front        88.6   168.8   64.1  ...              four   
1              front        88.6   168.8   64.1  ...              four   
2              front        94.5   171.2   65.5  ...               six   
3              front        99.8   176.6   66.2  ...              four   
4              front        99.4   176.6   66.4  ...              five   
...              ...         ...     ...    ...  ...               ...   
2045           front       109.1   188.8   68.9  ...              four   
2046           front       109.1   188.8   68.8  ...              four   
2047           front       109.1   188.8   68.9  ...               six   
2048           front       109.1   188.8   68.9  ...               six   
2049           front       109.1   188.8   68.9  ...              four   

      engine-size fuel-system  bore  stroke compression-ratio  horsepower  \
0             130        mpfi  3.47    2.68         10.779306       111.0   
1             130        mpfi  3.47    2.68         10.779306       111.0   
2             152        mpfi  2.68    3.47         10.779306       154.0   
3             109        mpfi  3.19    3.40         10.000000       102.0   
4             136        mpfi  3.19    3.40         10.779306       115.0   
...           ...         ...   ...     ...               ...         ...   
2045          141        mpfi  3.78    3.15          9.500000       114.0   
2046          141        mpfi  3.78    3.15          8.700000       160.0   
2047          173        mpfi  3.58    2.87          8.800000       134.0   
2048          145         idi  3.01    3.40         23.000000       106.0   
2049          141        mpfi  3.78    3.15          9.500000       114.0   

      peak-rpm  city-mpg  highway-mpg  
0       5000.0        21           27  
1       5000.0        21           27  
2       5000.0        19           26  
3       5500.0        24           30  
4       5500.0        18           22  
...        ...       ...          ...  
2045    5400.0        23           28  
2046    5300.0        19           25  
2047    5500.0        18           23  
2048    4800.0        26           27  
2049    5400.0        19           25  

[2050 rows x 23 columns]

In [6]:
y=d1['price']

In [7]:
y

0       13495.0
1       16500.0
2       16500.0
3       13950.0
4       17450.0
         ...   
2045    16845.0
2046    19045.0
2047    21485.0
2048    22470.0
2049    22625.0
Name: price, Length: 2050, dtype: float64

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le=LabelEncoder()

In [10]:
x[['car-name','fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','engine-type','num-of-cylinders','fuel-system']]=x[['car-name','fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','engine-type','num-of-cylinders','fuel-system']].apply(le.fit_transform)

In [11]:
x

car-name  fuel-type  aspiration  num-of-doors  body-style  drive-wheels  \
0            0          1           0             1           0             2   
1            0          1           0             1           0             2   
2            0          1           0             1           2             2   
3            1          1           0             0           3             1   
4            1          1           0             0           3             0   
...        ...        ...         ...           ...         ...           ...   
2045        21          1           0             0           3             2   
2046        21          1           1             0           3             2   
2047        21          1           0             0           3             2   
2048        21          0           1             0           3             2   
2049        21          1           1             0           3             2   

      engine-location  wheel-base  length  width  ...  num-of-cylinders  \
0                   0        88.6   168.8   64.1  ...                 2   
1                   0        88.6   168.8   64.1  ...                 2   
2                   0        94.5   171.2   65.5  ...                 3   
3                   0        99.8   176.6   66.2  ...                 2   
4                   0        99.4   176.6   66.4  ...                 1   
...               ...         ...     ...    ...  ...               ...   
2045                0       109.1   188.8   68.9  ...                 2   
2046                0       109.1   188.8   68.8  ...                 2   
2047                0       109.1   188.8   68.9  ...                 3   
2048                0       109.1   188.8   68.9  ...                 3   
2049                0       109.1   188.8   68.9  ...                 2   

      engine-size  fuel-system  bore  stroke  compression-ratio  horsepower  \
0             130            5  3.47    2.68          10.779306       111.0   
1             130            5  3.47    2.68          10.779306       111.0   
2             152            5  2.68    3.47          10.779306       154.0   
3             109            5  3.19    3.40          10.000000       102.0   
4             136            5  3.19    3.40          10.779306       115.0   
...           ...          ...   ...     ...                ...         ...   
2045          141            5  3.78    3.15           9.500000       114.0   
2046          141            5  3.78    3.15           8.700000       160.0   
2047          173            5  3.58    2.87           8.800000       134.0   
2048          145            3  3.01    3.40          23.000000       106.0   
2049          141            5  3.78    3.15           9.500000       114.0   

      peak-rpm  city-mpg  highway-mpg  
0       5000.0        21           27  
1       5000.0        21           27  
2       5000.0        19           26  
3       5500.0        24           30  
4       5500.0        18           22  
...        ...       ...          ...  
2045    5400.0        23           28  
2046    5300.0        19           25  
2047    5500.0        18           23  
2048    4800.0        26           27  
2049    5400.0        19           25  

[2050 rows x 23 columns]

In [12]:
y=le.fit_transform(y)

In [13]:
y

array([118, 137, 137, ..., 164, 166, 167], dtype=int64)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [16]:
from sklearn.neighbors import KNeighborsRegressor

In [17]:
knr=KNeighborsRegressor()

In [18]:
knr.fit(x_train,y_train)

KNeighborsRegressor()

In [19]:
y_pred=knr.predict(x_test)

In [20]:
y_pred

array([ 76.6, 106. , 177. , 133.2, 147. , 130. ,  99.4,  73. ,  52. ,
       102. ,  34. ,  64. ,  82. ,  86. ,  12. , 184. ,  71. ,  71. ,
       152. , 145.4, 116. ,  16. ,  16. , 134. , 153. , 169. , 178. ,
        39. ,  31.8,   1. ,  34. , 183. , 172. ,  49. , 114. ,   2. ,
        45. , 145.4,  99. ,  41. , 178. ,  48. , 113. ,  78. ,   1. ,
        34. , 183. ,  47. ,   7. ,  84. ,  58. ,   7. ,  42. ,   4. ,
        40. ,  30. , 157. ,  73. , 110. , 170. , 157. ,  14. ,  55. ,
       177. ,  18. ,  61. ,  99.4,  91. , 178. ,  99.4, 161. , 168. ,
        26. , 182. , 115. ,   4. , 173. , 186. ,  79. ,  28. , 139. ,
        53. ,  77. ,  27. , 109. , 185. ,  63. ,  95. , 145.4,  22. ,
       139. , 181. ,  89. ,  22. ,  27. ,  66. , 150. ,  40. , 157. ,
       148. , 126. ,  36.8,  19. , 182. , 100. ,  64. , 119. ,  72. ,
       133.2, 116. , 143. , 127. ,  74. ,  13. , 160. , 121. , 177. ,
       153. , 143. , 129. , 115. ,  59. ,  37. , 166. ,  52. , 177. ,
         8. ,  39. ,

In [21]:
y_test

array([ 87, 106, 176, 137, 147, 130,  94,  73,  52, 102,  34,  64,  82,
        86,  12, 184,  71,  71, 152, 144, 116,  16,  16, 134, 153, 169,
       178,  39,  11,   1,  34, 183, 172,  49, 114,   2,  45, 144,  99,
        41, 178,  48, 113,  78,   1,  34, 183,  47,   7,  84,  58,   7,
        42,   4,  40,  30, 157,  73, 110, 170, 157,  14,  55, 177,  18,
        61,  94,  91, 178,  94, 161, 168,  26, 182, 115,   4, 173, 186,
        79,  28, 139,  53,  77,  27, 109, 185,  63,  95, 151,  22, 139,
       181,  89,  22,  27,  66, 150,  40, 157, 148, 126,  20,  19, 182,
       100,  64, 119,  72, 137, 116, 143, 127,  74,  13, 160, 121, 175,
       153, 143, 129, 115,  59,  37, 166,  52, 180,   8,  39, 105,  10,
       142,   6, 160, 163, 120, 111,  36, 181,  65, 122, 119,  70,  12,
       110, 115, 172,  92, 144, 110,  83,  21,  53,  33, 121,  16,  80,
        96,  37,  17, 148, 115, 165, 143, 118, 125, 115,  74, 138,   9,
       130, 146, 150, 175, 136, 131, 161, 140, 185,  85, 132,  5

In [52]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [23]:
mse=mean_squared_error(y_test,y_pred)

In [24]:
mse

12.404487804878048

In [25]:
for k in range(1,20):
    knr=KNeighborsRegressor(n_neighbors=k)
    knr.fit(x_train,y_train)
    y_pred=knr.predict(x_test)
    mse=mean_squared_error(y_test,y_pred)
    print('k=',k,'mean_squared_error=',mse)

k= 1 mean_squared_error= 13.575609756097561
k= 2 mean_squared_error= 8.96280487804878
k= 3 mean_squared_error= 7.726287262872628
k= 4 mean_squared_error= 6.688871951219512
k= 5 mean_squared_error= 12.404487804878048
k= 6 mean_squared_error= 23.731978319783195
k= 7 mean_squared_error= 36.02633150821304
k= 8 mean_squared_error= 53.18506097560976
k= 9 mean_squared_error= 77.00716651610958
k= 10 mean_squared_error= 105.64782926829268
k= 11 mean_squared_error= 135.77544849828666
k= 12 mean_squared_error= 166.04517276422763
k= 13 mean_squared_error= 176.68363400202048
k= 14 mean_squared_error= 188.0321055251369
k= 15 mean_squared_error= 195.82269918699188
k= 16 mean_squared_error= 202.63922446646342
k= 17 mean_squared_error= 205.95236728837872
k= 18 mean_squared_error= 206.75979373682625
k= 19 mean_squared_error= 208.56808323761908


In [35]:
knr=KNeighborsRegressor(n_neighbors=4)

In [39]:
knr.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=4)

In [43]:
y_pred=knr.predict(x_test)

In [44]:
mse=mean_squared_error(y_test,y_pred)

In [53]:
print("MEAN-SQUARED-ERROR :",mse)

MEAN-SQUARED-ERROR : 6.688871951219512


In [54]:
r2c=r2_score(y_true=y_test, y_pred=y_pred)

In [55]:
print("R2-SCORE :",r2c)

R2-SCORE : 0.9977628119383593


In [49]:
mae=mean_absolute_error(y_test,y_pred)

In [56]:
print("MEAN-ABSOLUTE-ERROR :",mae)

MEAN-ABSOLUTE-ERROR : 0.5969512195121951
