In [1]:
import numpy as np
import pandas as pd

In [3]:
d1=pd.read_csv('New_Car_Automobile.csv')

In [4]:
d1

car-name fuel-type aspiration num-of-doors   body-style drive-wheels  \
0     alfa-romero       gas        std          two  convertible          rwd   
1     alfa-romero       gas        std          two  convertible          rwd   
2     alfa-romero       gas        std          two    hatchback          rwd   
3            audi       gas        std         four        sedan          fwd   
4            audi       gas        std         four        sedan          4wd   
...           ...       ...        ...          ...          ...          ...   
2045        volvo       gas        std         four        sedan          rwd   
2046        volvo       gas      turbo         four        sedan          rwd   
2047        volvo       gas        std         four        sedan          rwd   
2048        volvo    diesel      turbo         four        sedan          rwd   
2049        volvo       gas      turbo         four        sedan          rwd   

     engine-location  wheel-base  length  width  ...  engine-size  \
0              front        88.6   168.8   64.1  ...          130   
1              front        88.6   168.8   64.1  ...          130   
2              front        94.5   171.2   65.5  ...          152   
3              front        99.8   176.6   66.2  ...          109   
4              front        99.4   176.6   66.4  ...          136   
...              ...         ...     ...    ...  ...          ...   
2045           front       109.1   188.8   68.9  ...          141   
2046           front       109.1   188.8   68.8  ...          141   
2047           front       109.1   188.8   68.9  ...          173   
2048           front       109.1   188.8   68.9  ...          145   
2049           front       109.1   188.8   68.9  ...          141   

      fuel-system  bore stroke  compression-ratio horsepower  peak-rpm  \
0            mpfi  3.47   2.68          10.779306      111.0    5000.0   
1            mpfi  3.47   2.68          10.779306      111.0    5000.0   
2            mpfi  2.68   3.47          10.779306      154.0    5000.0   
3            mpfi  3.19   3.40          10.000000      102.0    5500.0   
4            mpfi  3.19   3.40          10.779306      115.0    5500.0   
...           ...   ...    ...                ...        ...       ...   
2045         mpfi  3.78   3.15           9.500000      114.0    5400.0   
2046         mpfi  3.78   3.15           8.700000      160.0    5300.0   
2047         mpfi  3.58   2.87           8.800000      134.0    5500.0   
2048          idi  3.01   3.40          23.000000      106.0    4800.0   
2049         mpfi  3.78   3.15           9.500000      114.0    5400.0   

      city-mpg  highway-mpg    price  
0           21           27  13495.0  
1           21           27  16500.0  
2           19           26  16500.0  
3           24           30  13950.0  
4           18           22  17450.0  
...        ...          ...      ...  
2045        23           28  16845.0  
2046        19           25  19045.0  
2047        18           23  21485.0  
2048        26           27  22470.0  
2049        19           25  22625.0  

[2050 rows x 24 columns]

In [5]:
d1.describe()

wheel-base       length        width       height  curb-weight  \
count  2050.000000  2050.000000  2050.000000  2050.000000  2050.000000   
mean     98.756585   174.049268    65.907805    53.724878  2555.565854   
std       6.008536    12.310164     2.140487     2.438150   519.535431   
min      86.600000   141.100000    60.300000    47.800000  1488.000000   
25%      94.500000   166.300000    64.100000    52.000000  2145.000000   
50%      97.000000   173.200000    65.500000    54.100000  2414.000000   
75%     102.400000   183.100000    66.900000    55.500000  2935.000000   
max     120.900000   208.100000    72.300000    59.800000  4066.000000   

       engine-size         bore       stroke  compression-ratio   horsepower  \
count  2050.000000  2050.000000  2050.000000        2050.000000  2050.000000   
mean    126.907317     3.329751     3.255423          10.779306   103.344188   
std      41.551137     0.270248     0.312908           3.822719    40.489081   
min      61.000000     2.540000     2.070000           7.500000    10.779306   
25%      97.000000     3.150000     3.110000           8.800000    70.000000   
50%     120.000000     3.310000     3.290000           9.500000    95.000000   
75%     141.000000     3.580000     3.410000          10.779306   116.000000   
max     326.000000     3.940000     4.170000          23.000000   288.000000   

          peak-rpm     city-mpg  highway-mpg         price  
count  2050.000000  2050.000000  2050.000000   2050.000000  
mean   5125.369458    25.219512    30.751220  13207.129353  
std     475.930402     6.527758     6.871303   7851.467858  
min    4150.000000    13.000000    16.000000   5118.000000  
25%    4800.000000    19.000000    25.000000   7788.000000  
50%    5200.000000    24.000000    30.000000  10595.000000  
75%    5500.000000    30.000000    34.000000  16500.000000  
max    6600.000000    49.000000    54.000000  45400.000000

In [6]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2050 entries, 0 to 2049
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   car-name           2050 non-null   object 
 1   fuel-type          2050 non-null   object 
 2   aspiration         2050 non-null   object 
 3   num-of-doors       2050 non-null   object 
 4   body-style         2050 non-null   object 
 5   drive-wheels       2050 non-null   object 
 6   engine-location    2050 non-null   object 
 7   wheel-base         2050 non-null   float64
 8   length             2050 non-null   float64
 9   width              2050 non-null   float64
 10  height             2050 non-null   float64
 11  curb-weight        2050 non-null   int64  
 12  engine-type        2050 non-null   object 
 13  num-of-cylinders   2050 non-null   object 
 14  engine-size        2050 non-null   int64  
 15  fuel-system        2050 non-null   object 
 16  bore               2050 

In [9]:
x=d1.drop('price',axis=1)

In [10]:
x

car-name fuel-type aspiration num-of-doors   body-style drive-wheels  \
0     alfa-romero       gas        std          two  convertible          rwd   
1     alfa-romero       gas        std          two  convertible          rwd   
2     alfa-romero       gas        std          two    hatchback          rwd   
3            audi       gas        std         four        sedan          fwd   
4            audi       gas        std         four        sedan          4wd   
...           ...       ...        ...          ...          ...          ...   
2045        volvo       gas        std         four        sedan          rwd   
2046        volvo       gas      turbo         four        sedan          rwd   
2047        volvo       gas        std         four        sedan          rwd   
2048        volvo    diesel      turbo         four        sedan          rwd   
2049        volvo       gas      turbo         four        sedan          rwd   

     engine-location  wheel-base  length  width  ...  num-of-cylinders  \
0              front        88.6   168.8   64.1  ...              four   
1              front        88.6   168.8   64.1  ...              four   
2              front        94.5   171.2   65.5  ...               six   
3              front        99.8   176.6   66.2  ...              four   
4              front        99.4   176.6   66.4  ...              five   
...              ...         ...     ...    ...  ...               ...   
2045           front       109.1   188.8   68.9  ...              four   
2046           front       109.1   188.8   68.8  ...              four   
2047           front       109.1   188.8   68.9  ...               six   
2048           front       109.1   188.8   68.9  ...               six   
2049           front       109.1   188.8   68.9  ...              four   

      engine-size fuel-system  bore  stroke compression-ratio  horsepower  \
0             130        mpfi  3.47    2.68         10.779306       111.0   
1             130        mpfi  3.47    2.68         10.779306       111.0   
2             152        mpfi  2.68    3.47         10.779306       154.0   
3             109        mpfi  3.19    3.40         10.000000       102.0   
4             136        mpfi  3.19    3.40         10.779306       115.0   
...           ...         ...   ...     ...               ...         ...   
2045          141        mpfi  3.78    3.15          9.500000       114.0   
2046          141        mpfi  3.78    3.15          8.700000       160.0   
2047          173        mpfi  3.58    2.87          8.800000       134.0   
2048          145         idi  3.01    3.40         23.000000       106.0   
2049          141        mpfi  3.78    3.15          9.500000       114.0   

      peak-rpm  city-mpg  highway-mpg  
0       5000.0        21           27  
1       5000.0        21           27  
2       5000.0        19           26  
3       5500.0        24           30  
4       5500.0        18           22  
...        ...       ...          ...  
2045    5400.0        23           28  
2046    5300.0        19           25  
2047    5500.0        18           23  
2048    4800.0        26           27  
2049    5400.0        19           25  

[2050 rows x 23 columns]

In [11]:
y=d1['price']

In [12]:
y

0       13495.0
1       16500.0
2       16500.0
3       13950.0
4       17450.0
         ...   
2045    16845.0
2046    19045.0
2047    21485.0
2048    22470.0
2049    22625.0
Name: price, Length: 2050, dtype: float64

In [24]:
d1['car-name'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [26]:
d1['car-name'].value_counts()

toyota           320
nissan           180
mazda            170
mitsubishi       130
honda            130
volkswagen       120
subaru           120
peugot           110
volvo            110
dodge             90
mercedes-benz     80
bmw               80
audi              70
plymouth          70
saab              60
porsche           50
isuzu             40
jaguar            30
alfa-romero       30
chevrolet         30
renault           20
mercury           10
Name: car-name, dtype: int64

In [27]:
d1['fuel-type'].value_counts()

gas       1850
diesel     200
Name: fuel-type, dtype: int64

In [28]:
d1['aspiration'].unique()

array(['std', 'turbo'], dtype=object)

In [29]:
d1['num-of-doors'].unique()

array(['two', 'four'], dtype=object)

In [30]:
d1['body-style'].unique()

array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object)

In [31]:
d1['drive-wheels'].unique()

array(['rwd', 'fwd', '4wd'], dtype=object)

In [32]:
d1['engine-location'].unique()

array(['front', 'rear'], dtype=object)

In [33]:
d1['fuel-system'].unique()

array(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'],
      dtype=object)

In [67]:
d1['engine-type'].unique()

array(['dohc', 'ohcv', 'ohc', 'rotor', 'ohcf', 'dohcv'], dtype=object)

In [69]:
d1['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [34]:
# So here as all columns consist of categorical data we will be encoding them 
# using the label Encoder technic
# the Label Encoder Technique will assign a number starting from Zero 
# to the unique values in the data

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
le=LabelEncoder()

In [70]:
x[['car-name','fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','engine-type','num-of-cylinders','fuel-system']]=x[['car-name','fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','engine-type','num-of-cylinders','fuel-system']].apply(le.fit_transform)

In [71]:
x

car-name  fuel-type  aspiration  num-of-doors  body-style  drive-wheels  \
0            0          1           0             1           0             2   
1            0          1           0             1           0             2   
2            0          1           0             1           2             2   
3            1          1           0             0           3             1   
4            1          1           0             0           3             0   
...        ...        ...         ...           ...         ...           ...   
2045        21          1           0             0           3             2   
2046        21          1           1             0           3             2   
2047        21          1           0             0           3             2   
2048        21          0           1             0           3             2   
2049        21          1           1             0           3             2   

      engine-location  wheel-base  length  width  ...  num-of-cylinders  \
0                   0        88.6   168.8   64.1  ...                 2   
1                   0        88.6   168.8   64.1  ...                 2   
2                   0        94.5   171.2   65.5  ...                 3   
3                   0        99.8   176.6   66.2  ...                 2   
4                   0        99.4   176.6   66.4  ...                 1   
...               ...         ...     ...    ...  ...               ...   
2045                0       109.1   188.8   68.9  ...                 2   
2046                0       109.1   188.8   68.8  ...                 2   
2047                0       109.1   188.8   68.9  ...                 3   
2048                0       109.1   188.8   68.9  ...                 3   
2049                0       109.1   188.8   68.9  ...                 2   

      engine-size  fuel-system  bore  stroke  compression-ratio  horsepower  \
0             130            5  3.47    2.68          10.779306       111.0   
1             130            5  3.47    2.68          10.779306       111.0   
2             152            5  2.68    3.47          10.779306       154.0   
3             109            5  3.19    3.40          10.000000       102.0   
4             136            5  3.19    3.40          10.779306       115.0   
...           ...          ...   ...     ...                ...         ...   
2045          141            5  3.78    3.15           9.500000       114.0   
2046          141            5  3.78    3.15           8.700000       160.0   
2047          173            5  3.58    2.87           8.800000       134.0   
2048          145            3  3.01    3.40          23.000000       106.0   
2049          141            5  3.78    3.15           9.500000       114.0   

      peak-rpm  city-mpg  highway-mpg  
0       5000.0        21           27  
1       5000.0        21           27  
2       5000.0        19           26  
3       5500.0        24           30  
4       5500.0        18           22  
...        ...       ...          ...  
2045    5400.0        23           28  
2046    5300.0        19           25  
2047    5500.0        18           23  
2048    4800.0        26           27  
2049    5400.0        19           25  

[2050 rows x 23 columns]

In [72]:
# so now all the columns are in numeric from
# if we want to get know what numbers it has has assigned to which to which values 
old_values=le.classes_

In [73]:
old_values

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [74]:
le.classes_

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [75]:
y=le.fit_transform(y)

In [76]:
y

array([118, 137, 137, ..., 164, 166, 167], dtype=int64)

In [77]:
from sklearn.model_selection import train_test_split

In [78]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [79]:
x_train.shape

(1640, 23)

In [80]:
x_test.shape

(410, 23)

In [81]:
y_train.shape

(1640,)

In [82]:
y_test.shape

(410,)

In [83]:
from sklearn.neighbors import KNeighborsRegressor

In [84]:
knr=KNeighborsRegressor()

In [85]:
knr.fit(x_train,y_train)

KNeighborsRegressor()

In [86]:
y_pred=knr.predict(x_test)

In [87]:
y_pred

array([ 76.6, 106. , 177. , 133.2, 147. , 130. ,  99.4,  73. ,  52. ,
       102. ,  34. ,  64. ,  82. ,  86. ,  12. , 184. ,  71. ,  71. ,
       152. , 145.4, 116. ,  16. ,  16. , 134. , 153. , 169. , 178. ,
        39. ,  31.8,   1. ,  34. , 183. , 172. ,  49. , 114. ,   2. ,
        45. , 145.4,  99. ,  41. , 178. ,  48. , 113. ,  78. ,   1. ,
        34. , 183. ,  47. ,   7. ,  84. ,  58. ,   7. ,  42. ,   4. ,
        40. ,  30. , 157. ,  73. , 110. , 170. , 157. ,  14. ,  55. ,
       177. ,  18. ,  61. ,  99.4,  91. , 178. ,  99.4, 161. , 168. ,
        26. , 182. , 115. ,   4. , 173. , 186. ,  79. ,  28. , 139. ,
        53. ,  77. ,  27. , 109. , 185. ,  63. ,  95. , 145.4,  22. ,
       139. , 181. ,  89. ,  22. ,  27. ,  66. , 150. ,  40. , 157. ,
       148. , 126. ,  36.8,  19. , 182. , 100. ,  64. , 119. ,  72. ,
       133.2, 116. , 143. , 127. ,  74. ,  13. , 160. , 121. , 177. ,
       153. , 143. , 129. , 115. ,  59. ,  37. , 166. ,  52. , 177. ,
         8. ,  39. ,

In [88]:
y_test

array([ 87, 106, 176, 137, 147, 130,  94,  73,  52, 102,  34,  64,  82,
        86,  12, 184,  71,  71, 152, 144, 116,  16,  16, 134, 153, 169,
       178,  39,  11,   1,  34, 183, 172,  49, 114,   2,  45, 144,  99,
        41, 178,  48, 113,  78,   1,  34, 183,  47,   7,  84,  58,   7,
        42,   4,  40,  30, 157,  73, 110, 170, 157,  14,  55, 177,  18,
        61,  94,  91, 178,  94, 161, 168,  26, 182, 115,   4, 173, 186,
        79,  28, 139,  53,  77,  27, 109, 185,  63,  95, 151,  22, 139,
       181,  89,  22,  27,  66, 150,  40, 157, 148, 126,  20,  19, 182,
       100,  64, 119,  72, 137, 116, 143, 127,  74,  13, 160, 121, 175,
       153, 143, 129, 115,  59,  37, 166,  52, 180,   8,  39, 105,  10,
       142,   6, 160, 163, 120, 111,  36, 181,  65, 122, 119,  70,  12,
       110, 115, 172,  92, 144, 110,  83,  21,  53,  33, 121,  16,  80,
        96,  37,  17, 148, 115, 165, 143, 118, 125, 115,  74, 138,   9,
       130, 146, 150, 175, 136, 131, 161, 140, 185,  85, 132,  5

In [89]:
from sklearn.metrics import mean_squared_error

In [93]:
mse=mean_squared_error(y_test,y_pred)

In [94]:
mse

12.404487804878048

In [96]:
for k in range(1,20):
    knr=KNeighborsRegressor(n_neighbors=k)
    knr.fit(x_train,y_train)
    y_pred=knr.predict(x_test)
    mse=mean_squared_error(y_test,y_pred)
    print('k=',k,'mean_squared_error=',mse)

k= 1 mean_squared_error= 13.575609756097561
k= 2 mean_squared_error= 8.96280487804878
k= 3 mean_squared_error= 7.726287262872628
k= 4 mean_squared_error= 6.688871951219512
k= 5 mean_squared_error= 12.404487804878048
k= 6 mean_squared_error= 23.731978319783195
k= 7 mean_squared_error= 36.02633150821304
k= 8 mean_squared_error= 53.18506097560976
k= 9 mean_squared_error= 77.00716651610958
k= 10 mean_squared_error= 105.64782926829268
k= 11 mean_squared_error= 135.77544849828666
k= 12 mean_squared_error= 166.04517276422763
k= 13 mean_squared_error= 176.68363400202048
k= 14 mean_squared_error= 188.0321055251369
k= 15 mean_squared_error= 195.82269918699188
k= 16 mean_squared_error= 202.63922446646342
k= 17 mean_squared_error= 205.95236728837872
k= 18 mean_squared_error= 206.75979373682625
k= 19 mean_squared_error= 208.56808323761908


In [97]:
knr=KNeighborsRegressor(n_neighbors=4)

In [98]:
knr.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=4)

In [99]:
y_pred=knr.predict(x_test)

In [100]:
y_pred

array([ 74.  , 106.  , 177.  , 132.25, 147.  , 130.  ,  98.5 ,  73.  ,
        52.  , 102.  ,  34.  ,  64.  ,  82.  ,  86.  ,  12.  , 184.  ,
        71.  ,  71.  , 152.  , 145.75, 116.  ,  16.  ,  16.  , 134.  ,
       153.  , 169.  , 178.  ,  39.  ,  11.  ,   1.  ,  34.  , 183.  ,
       172.  ,  49.  , 114.  ,   2.  ,  45.  , 145.75,  99.  ,  41.  ,
       178.  ,  48.  , 113.  ,  78.  ,   1.  ,  34.  , 183.  ,  47.  ,
         7.  ,  84.  ,  58.  ,   7.  ,  42.  ,   4.  ,  40.  ,  30.  ,
       157.  ,  73.  , 110.  , 170.  , 157.  ,  14.  ,  55.  , 177.  ,
        18.  ,  61.  ,  98.5 ,  91.  , 178.  ,  98.5 , 161.  , 168.  ,
        26.  , 182.  , 115.  ,   4.  , 173.  , 186.  ,  79.  ,  28.  ,
       139.  ,  53.  ,  77.  ,  27.  , 109.  , 185.  ,  63.  ,  95.  ,
       145.75,  22.  , 139.  , 181.  ,  89.  ,  22.  ,  27.  ,  66.  ,
       150.  ,  40.  , 157.  , 148.  , 126.  ,  35.75,  19.  , 182.  ,
       100.  ,  64.  , 119.  ,  72.  , 132.25, 116.  , 143.  , 127.  ,
      

In [101]:
y_test

array([ 87, 106, 176, 137, 147, 130,  94,  73,  52, 102,  34,  64,  82,
        86,  12, 184,  71,  71, 152, 144, 116,  16,  16, 134, 153, 169,
       178,  39,  11,   1,  34, 183, 172,  49, 114,   2,  45, 144,  99,
        41, 178,  48, 113,  78,   1,  34, 183,  47,   7,  84,  58,   7,
        42,   4,  40,  30, 157,  73, 110, 170, 157,  14,  55, 177,  18,
        61,  94,  91, 178,  94, 161, 168,  26, 182, 115,   4, 173, 186,
        79,  28, 139,  53,  77,  27, 109, 185,  63,  95, 151,  22, 139,
       181,  89,  22,  27,  66, 150,  40, 157, 148, 126,  20,  19, 182,
       100,  64, 119,  72, 137, 116, 143, 127,  74,  13, 160, 121, 175,
       153, 143, 129, 115,  59,  37, 166,  52, 180,   8,  39, 105,  10,
       142,   6, 160, 163, 120, 111,  36, 181,  65, 122, 119,  70,  12,
       110, 115, 172,  92, 144, 110,  83,  21,  53,  33, 121,  16,  80,
        96,  37,  17, 148, 115, 165, 143, 118, 125, 115,  74, 138,   9,
       130, 146, 150, 175, 136, 131, 161, 140, 185,  85, 132,  5

In [102]:
mse=mean_squared_error(y_test,y_pred)

In [103]:
mse

6.688871951219512