In [1]:
import pandas as pd
import numpy as np


In [2]:
data=pd.read_csv('New_Car_Automobile.csv')

In [3]:
data

car-name fuel-type aspiration num-of-doors   body-style drive-wheels  \
0     alfa-romero       gas        std          two  convertible          rwd   
1     alfa-romero       gas        std          two  convertible          rwd   
2     alfa-romero       gas        std          two    hatchback          rwd   
3            audi       gas        std         four        sedan          fwd   
4            audi       gas        std         four        sedan          4wd   
...           ...       ...        ...          ...          ...          ...   
2045        volvo       gas        std         four        sedan          rwd   
2046        volvo       gas      turbo         four        sedan          rwd   
2047        volvo       gas        std         four        sedan          rwd   
2048        volvo    diesel      turbo         four        sedan          rwd   
2049        volvo       gas      turbo         four        sedan          rwd   

     engine-location  wheel-base  length  width  ...  engine-size  \
0              front        88.6   168.8   64.1  ...          130   
1              front        88.6   168.8   64.1  ...          130   
2              front        94.5   171.2   65.5  ...          152   
3              front        99.8   176.6   66.2  ...          109   
4              front        99.4   176.6   66.4  ...          136   
...              ...         ...     ...    ...  ...          ...   
2045           front       109.1   188.8   68.9  ...          141   
2046           front       109.1   188.8   68.8  ...          141   
2047           front       109.1   188.8   68.9  ...          173   
2048           front       109.1   188.8   68.9  ...          145   
2049           front       109.1   188.8   68.9  ...          141   

      fuel-system  bore stroke  compression-ratio horsepower  peak-rpm  \
0            mpfi  3.47   2.68          10.779306      111.0    5000.0   
1            mpfi  3.47   2.68          10.779306      111.0    5000.0   
2            mpfi  2.68   3.47          10.779306      154.0    5000.0   
3            mpfi  3.19   3.40          10.000000      102.0    5500.0   
4            mpfi  3.19   3.40          10.779306      115.0    5500.0   
...           ...   ...    ...                ...        ...       ...   
2045         mpfi  3.78   3.15           9.500000      114.0    5400.0   
2046         mpfi  3.78   3.15           8.700000      160.0    5300.0   
2047         mpfi  3.58   2.87           8.800000      134.0    5500.0   
2048          idi  3.01   3.40          23.000000      106.0    4800.0   
2049         mpfi  3.78   3.15           9.500000      114.0    5400.0   

      city-mpg  highway-mpg    price  
0           21           27  13495.0  
1           21           27  16500.0  
2           19           26  16500.0  
3           24           30  13950.0  
4           18           22  17450.0  
...        ...          ...      ...  
2045        23           28  16845.0  
2046        19           25  19045.0  
2047        18           23  21485.0  
2048        26           27  22470.0  
2049        19           25  22625.0  

[2050 rows x 24 columns]

In [4]:
x=data.drop('price',axis=1)

In [5]:
x

car-name fuel-type aspiration num-of-doors   body-style drive-wheels  \
0     alfa-romero       gas        std          two  convertible          rwd   
1     alfa-romero       gas        std          two  convertible          rwd   
2     alfa-romero       gas        std          two    hatchback          rwd   
3            audi       gas        std         four        sedan          fwd   
4            audi       gas        std         four        sedan          4wd   
...           ...       ...        ...          ...          ...          ...   
2045        volvo       gas        std         four        sedan          rwd   
2046        volvo       gas      turbo         four        sedan          rwd   
2047        volvo       gas        std         four        sedan          rwd   
2048        volvo    diesel      turbo         four        sedan          rwd   
2049        volvo       gas      turbo         four        sedan          rwd   

     engine-location  wheel-base  length  width  ...  num-of-cylinders  \
0              front        88.6   168.8   64.1  ...              four   
1              front        88.6   168.8   64.1  ...              four   
2              front        94.5   171.2   65.5  ...               six   
3              front        99.8   176.6   66.2  ...              four   
4              front        99.4   176.6   66.4  ...              five   
...              ...         ...     ...    ...  ...               ...   
2045           front       109.1   188.8   68.9  ...              four   
2046           front       109.1   188.8   68.8  ...              four   
2047           front       109.1   188.8   68.9  ...               six   
2048           front       109.1   188.8   68.9  ...               six   
2049           front       109.1   188.8   68.9  ...              four   

      engine-size fuel-system  bore  stroke compression-ratio  horsepower  \
0             130        mpfi  3.47    2.68         10.779306       111.0   
1             130        mpfi  3.47    2.68         10.779306       111.0   
2             152        mpfi  2.68    3.47         10.779306       154.0   
3             109        mpfi  3.19    3.40         10.000000       102.0   
4             136        mpfi  3.19    3.40         10.779306       115.0   
...           ...         ...   ...     ...               ...         ...   
2045          141        mpfi  3.78    3.15          9.500000       114.0   
2046          141        mpfi  3.78    3.15          8.700000       160.0   
2047          173        mpfi  3.58    2.87          8.800000       134.0   
2048          145         idi  3.01    3.40         23.000000       106.0   
2049          141        mpfi  3.78    3.15          9.500000       114.0   

      peak-rpm  city-mpg  highway-mpg  
0       5000.0        21           27  
1       5000.0        21           27  
2       5000.0        19           26  
3       5500.0        24           30  
4       5500.0        18           22  
...        ...       ...          ...  
2045    5400.0        23           28  
2046    5300.0        19           25  
2047    5500.0        18           23  
2048    4800.0        26           27  
2049    5400.0        19           25  

[2050 rows x 23 columns]

In [7]:
y=data['price']

In [8]:
y

0       13495.0
1       16500.0
2       16500.0
3       13950.0
4       17450.0
         ...   
2045    16845.0
2046    19045.0
2047    21485.0
2048    22470.0
2049    22625.0
Name: price, Length: 2050, dtype: float64

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le=LabelEncoder()

In [11]:
x[['car-name','fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','engine-type','num-of-cylinders','fuel-system']]=x[['car-name','fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','engine-type','num-of-cylinders','fuel-system']].apply(le.fit_transform)

In [12]:
x

car-name  fuel-type  aspiration  num-of-doors  body-style  drive-wheels  \
0            0          1           0             1           0             2   
1            0          1           0             1           0             2   
2            0          1           0             1           2             2   
3            1          1           0             0           3             1   
4            1          1           0             0           3             0   
...        ...        ...         ...           ...         ...           ...   
2045        21          1           0             0           3             2   
2046        21          1           1             0           3             2   
2047        21          1           0             0           3             2   
2048        21          0           1             0           3             2   
2049        21          1           1             0           3             2   

      engine-location  wheel-base  length  width  ...  num-of-cylinders  \
0                   0        88.6   168.8   64.1  ...                 2   
1                   0        88.6   168.8   64.1  ...                 2   
2                   0        94.5   171.2   65.5  ...                 3   
3                   0        99.8   176.6   66.2  ...                 2   
4                   0        99.4   176.6   66.4  ...                 1   
...               ...         ...     ...    ...  ...               ...   
2045                0       109.1   188.8   68.9  ...                 2   
2046                0       109.1   188.8   68.8  ...                 2   
2047                0       109.1   188.8   68.9  ...                 3   
2048                0       109.1   188.8   68.9  ...                 3   
2049                0       109.1   188.8   68.9  ...                 2   

      engine-size  fuel-system  bore  stroke  compression-ratio  horsepower  \
0             130            5  3.47    2.68          10.779306       111.0   
1             130            5  3.47    2.68          10.779306       111.0   
2             152            5  2.68    3.47          10.779306       154.0   
3             109            5  3.19    3.40          10.000000       102.0   
4             136            5  3.19    3.40          10.779306       115.0   
...           ...          ...   ...     ...                ...         ...   
2045          141            5  3.78    3.15           9.500000       114.0   
2046          141            5  3.78    3.15           8.700000       160.0   
2047          173            5  3.58    2.87           8.800000       134.0   
2048          145            3  3.01    3.40          23.000000       106.0   
2049          141            5  3.78    3.15           9.500000       114.0   

      peak-rpm  city-mpg  highway-mpg  
0       5000.0        21           27  
1       5000.0        21           27  
2       5000.0        19           26  
3       5500.0        24           30  
4       5500.0        18           22  
...        ...       ...          ...  
2045    5400.0        23           28  
2046    5300.0        19           25  
2047    5500.0        18           23  
2048    4800.0        26           27  
2049    5400.0        19           25  

[2050 rows x 23 columns]

In [25]:
y=le.fit_transform(y)

In [26]:
y

array([118, 137, 137, ..., 164, 166, 167], dtype=int64)

In [27]:
# Model Implementation --> Creation, Fit(Training) and Prediction

In [28]:
# Importing the model
from sklearn.tree import DecisionTreeRegressor

In [29]:
# Createing the object
dtc = DecisionTreeRegressor()     

In [30]:
# Train the model using fit function
dtc.fit(x,y)

DecisionTreeRegressor()

In [31]:
# prredict on x dataset
y_pred = dtc.predict(x)

In [35]:
y_pred

array([127.5, 127.5, 137. , ..., 164. , 166. , 167. ])

In [36]:
y

array([118, 137, 137, ..., 164, 166, 167], dtype=int64)

In [37]:
# Evaluate
from sklearn.metrics import mean_squared_error


In [38]:
mse = mean_squared_error(y,y_pred)

In [40]:
mse

5.509756097560976